// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRHFyPbRyDpPwJQZLFpTqTDdlfAzXIt5k',
    appId: '1:366556236216:web:051e371cca771c231e274d',
    messagingSenderId: '366556236216',
    projectId: 'falmily-582da',
    authDomain: 'falmily-582da.firebaseapp.com',
    storageBucket: 'falmily-582da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLAgoiNZjGI4fQf29GNnlL5mhnCh6bfis',
    appId: '1:366556236216:android:4f945393bc1f4e461e274d',
    messagingSenderId: '366556236216',
    projectId: 'falmily-582da',
    storageBucket: 'falmily-582da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbPFdN3djzDfOBsc-CWP9hlXN4JmtRssc',
    appId: '1:366556236216:ios:febbb8a0d5292a5a1e274d',
    messagingSenderId: '366556236216',
    projectId: 'falmily-582da',
    storageBucket: 'falmily-582da.appspot.com',
    iosBundleId: 'com.example.falmily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbPFdN3djzDfOBsc-CWP9hlXN4JmtRssc',
    appId: '1:366556236216:ios:febbb8a0d5292a5a1e274d',
    messagingSenderId: '366556236216',
    projectId: 'falmily-582da',
    storageBucket: 'falmily-582da.appspot.com',
    iosBundleId: 'com.example.falmily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRHFyPbRyDpPwJQZLFpTqTDdlfAzXIt5k',
    appId: '1:366556236216:web:d6236f84f33073f71e274d',
    messagingSenderId: '366556236216',
    projectId: 'falmily-582da',
    authDomain: 'falmily-582da.firebaseapp.com',
    storageBucket: 'falmily-582da.appspot.com',
  );
}
